source 'https://cdn.cocoapods.org'

platform :ios, '10.0'
use_frameworks!

target 'ProtocolServiceKit_Demo_Example' do
    
  puts "make sure you can open GitHub website！"
  
  pod 'ProtocolServiceKit', :path => '../'
  
  pod 'AccountBusiness',:git => "https://github.com/Todaycoding/ProtocolServiceKit-AccountMoudle.git"
  
  pod 'PlayBusiness',:git => "https://github.com/Todaycoding/ProtocolServiceKit-PlayMoudle.git"

end
