source 'https://github.com/Todaycoding/DragonSpecs.git'
source 'https://cdn.cocoapods.org'

platform :ios, '10.0'

target 'ProtocolServiceKit_Demo_Example' do
  use_frameworks!
  pod 'ProtocolServiceKit', :path => '../'
  pod 'AccountBusiness'
  pod 'PlayBusiness'

end
