use_frameworks!

platform :ios, '10.0'

target 'ProtocolServiceManger_Example' do
  pod 'ProtocolServiceKit', :path => '../'
  pod 'AccountBusiness', :path => './localPod'
  pod 'PlayBusiness', :path => './localPod'
  

end
